dist: bionic
language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

addons:
  sonarcloud:
    organization: smbla
    token: 573a056744e27e984d2514e1770c5251649da522
script:
  - sonar-scanner
  - python -m pytest --cov=a
after_success:
  - coveralls
