dist: bionic
language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

addons:
  sonarcloud:
    organization: smbla
    token:
      secure: 2a37a04ae208e8fa6b088cb41504fec568d4ba90
script:
  - sonar-scanner
  - pytest --cov=sm
after_success:
  - coveralls